### ISSUE TITLE
Could not get model name from scanner

### ISSUE THREAD

**Issue by chlorinekid** [fdev/bc125csv#2]
Have managed to install this on Xubuntu 18.04 but when trying to run the following code:

`sudo bc125csv export -s -b 1 2 3 4 5 6 7 8 9 10 > banks-1234.csv`

I'm getting the error:

`Could not get model name from scanner`

Have a UBC125XLT connected. Is there a way to manually override the model number in the code?

**Comment by fdev** [comment]
The model number check is not only used for verifying a supported device is connected, but also a way to make sure the connection to the device is working correctly. Bypassing the model check will most likely result in the export not working either.

I'll try to reproduce the error using my UBC125XLT as soon I have some spare time.

**Comment by chlorinekid** [comment]
I've found that I always get this error when trying to export from the scanner after plugging it in - however running the same command a second time straight after seems to work. I can export the csv file and then upload it a few minutes later no problem.

**Comment by fdev** [comment]
I suspect the `ModemManager` service thinks the scanner is a modem and tries to claim the device, only to release it after some time. You can see this happening in the logs by typing:

```
sudo systemctl status ModemManager
````

To prevent the `ModemManager` from claiming the device you can stop it. After entering the following command the scanner export should happen instantly like expected:

```
sudo systemctl stop ModemManager
```

To **permanently** disable the `ModemManager` from starting automatically, you can use:

```
sudo systemctl disable ModemManager
```

Can you let me know if this has fixed the issue for you?

**Comment by chlorinekid** [comment]
That appears to solve the issue, yes. I stopped the service and was able to export first time. Thanks.
